on:
  push: {}

jobs:
  tests:
    name: run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.23
      - uses: actions/checkout@v3
      - run: go mod tidy && go mod vendor
      - run: go test -v -race ./...
